name: powered_by_obsdiv
description: "Powered by OBSDIV - AI image generator app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.11
  share_plus: ^10.0.2
  image_gallery_saver_plus: ^4.0.1
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  provider: ^6.1.2
  flutter_tts: ^3.8.3
  audioplayers: ^6.0.0
  meta: ^1.12.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logos/
    - lib/assets/backgrounds/
    - lib/assets/icons/
    - lib/assets/mockups/
    - .env
    - lib/assets/logos/Obsdiv.jpg
